2023-04-19 23:38:27,370 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Configure stats pid to 8641
2023-04-19 23:38:27,370 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from /Users/malujie/.config/wandb/settings
2023-04-19 23:38:27,370 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from /Users/Uni Course/IML/IML_A3/wandb/settings
2023-04-19 23:38:27,370 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-19 23:38:27,370 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-04-19 23:38:27,370 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-04-19 23:38:27,371 INFO    MainThread:8641 [wandb_init.py:_log_setup():507] Logging user logs to /Users/Uni Course/IML/IML_A3/wandb/run-20230419_233827-csrclmxe/logs/debug.log
2023-04-19 23:38:27,371 INFO    MainThread:8641 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/Uni Course/IML/IML_A3/wandb/run-20230419_233827-csrclmxe/logs/debug-internal.log
2023-04-19 23:38:27,371 INFO    MainThread:8641 [wandb_init.py:_jupyter_setup():453] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fc02246f9a0>
2023-04-19 23:38:27,371 INFO    MainThread:8641 [wandb_init.py:init():547] calling init triggers
2023-04-19 23:38:27,372 INFO    MainThread:8641 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-04-19 23:38:27,372 INFO    MainThread:8641 [wandb_init.py:init():595] starting backend
2023-04-19 23:38:27,372 INFO    MainThread:8641 [wandb_init.py:init():599] setting up manager
2023-04-19 23:38:27,390 INFO    MainThread:8641 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-04-19 23:38:27,509 INFO    MainThread:8641 [wandb_init.py:init():605] backend started and connected
2023-04-19 23:38:27,530 INFO    MainThread:8641 [wandb_run.py:_label_probe_notebook():1237] probe notebook
2023-04-19 23:38:27,532 INFO    MainThread:8641 [wandb_run.py:_label_probe_notebook():1247] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-04-19 23:38:27,532 INFO    MainThread:8641 [wandb_init.py:init():695] updated telemetry
2023-04-19 23:38:27,555 INFO    MainThread:8641 [wandb_init.py:init():732] communicating run to backend with 60.0 second timeout
2023-04-19 23:38:29,834 ERROR   MainThread:8641 [wandb_init.py:init():758] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2023-04-19 23:38:29,934 ERROR   MainThread:8641 [wandb_init.py:init():1163] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1145, in init
    run = wi.init()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 764, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2023-04-19 23:38:42,810 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Configure stats pid to 8641
2023-04-19 23:38:42,810 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from /Users/malujie/.config/wandb/settings
2023-04-19 23:38:42,811 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from /Users/Uni Course/IML/IML_A3/wandb/settings
2023-04-19 23:38:42,811 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-19 23:38:42,811 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-04-19 23:38:42,811 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-04-19 23:38:42,811 INFO    MainThread:8641 [wandb_init.py:_log_setup():507] Logging user logs to /Users/Uni Course/IML/IML_A3/wandb/run-20230419_233842-bgy75cim/logs/debug.log
2023-04-19 23:38:42,811 INFO    MainThread:8641 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/Uni Course/IML/IML_A3/wandb/run-20230419_233842-bgy75cim/logs/debug-internal.log
2023-04-19 23:38:42,811 INFO    MainThread:8641 [wandb_init.py:init():547] calling init triggers
2023-04-19 23:38:42,811 INFO    MainThread:8641 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-04-19 23:38:42,811 INFO    MainThread:8641 [wandb_init.py:init():595] starting backend
2023-04-19 23:38:42,811 INFO    MainThread:8641 [wandb_init.py:init():599] setting up manager
2023-04-19 23:38:42,814 INFO    MainThread:8641 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-04-19 23:38:42,816 INFO    MainThread:8641 [wandb_init.py:init():605] backend started and connected
2023-04-19 23:38:42,827 INFO    MainThread:8641 [wandb_run.py:_label_probe_notebook():1237] probe notebook
2023-04-19 23:38:42,827 INFO    MainThread:8641 [wandb_run.py:_label_probe_notebook():1247] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-04-19 23:38:42,827 INFO    MainThread:8641 [wandb_init.py:init():695] updated telemetry
2023-04-19 23:38:42,849 INFO    MainThread:8641 [wandb_init.py:init():732] communicating run to backend with 60.0 second timeout
2023-04-19 23:38:44,345 WARNING MsgRouterThr:8641 [router.py:message_loop():77] message_loop has been closed
2023-04-19 23:39:43,071 ERROR   MainThread:8641 [wandb_init.py:init():758] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-04-19 23:39:43,109 ERROR   MainThread:8641 [wandb_init.py:init():1163] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1145, in init
    run = wi.init()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 764, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-04-19 23:41:25,888 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Configure stats pid to 8641
2023-04-19 23:41:25,888 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from /Users/malujie/.config/wandb/settings
2023-04-19 23:41:25,889 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from /Users/Uni Course/IML/IML_A3/wandb/settings
2023-04-19 23:41:25,889 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-19 23:41:25,889 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-04-19 23:41:25,889 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-04-19 23:41:25,890 INFO    MainThread:8641 [wandb_init.py:_log_setup():507] Logging user logs to /Users/Uni Course/IML/IML_A3/wandb/run-20230419_234125-cscec6qs/logs/debug.log
2023-04-19 23:41:25,890 INFO    MainThread:8641 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/Uni Course/IML/IML_A3/wandb/run-20230419_234125-cscec6qs/logs/debug-internal.log
2023-04-19 23:41:25,890 INFO    MainThread:8641 [wandb_init.py:init():547] calling init triggers
2023-04-19 23:41:25,890 INFO    MainThread:8641 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-04-19 23:41:25,891 INFO    MainThread:8641 [wandb_init.py:init():595] starting backend
2023-04-19 23:41:25,891 INFO    MainThread:8641 [wandb_init.py:init():599] setting up manager
2023-04-19 23:41:25,901 INFO    MainThread:8641 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-04-19 23:41:25,905 INFO    MainThread:8641 [wandb_init.py:init():605] backend started and connected
2023-04-19 23:41:25,919 INFO    MainThread:8641 [wandb_run.py:_label_probe_notebook():1237] probe notebook
2023-04-19 23:41:25,919 INFO    MainThread:8641 [wandb_run.py:_label_probe_notebook():1247] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-04-19 23:41:25,919 INFO    MainThread:8641 [wandb_init.py:init():695] updated telemetry
2023-04-19 23:41:25,966 INFO    MainThread:8641 [wandb_init.py:init():732] communicating run to backend with 60.0 second timeout
2023-04-19 23:42:26,179 ERROR   MainThread:8641 [wandb_init.py:init():758] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-04-19 23:42:26,204 ERROR   MainThread:8641 [wandb_init.py:init():1163] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1145, in init
    run = wi.init()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 764, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-04-19 23:43:20,901 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Configure stats pid to 8641
2023-04-19 23:43:20,901 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from /Users/malujie/.config/wandb/settings
2023-04-19 23:43:20,901 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from /Users/Uni Course/IML/IML_A3/wandb/settings
2023-04-19 23:43:20,901 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-19 23:43:20,901 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-04-19 23:43:20,901 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-04-19 23:43:20,902 INFO    MainThread:8641 [wandb_init.py:_log_setup():507] Logging user logs to /Users/Uni Course/IML/IML_A3/wandb/run-20230419_234320-zgbe7e2n/logs/debug.log
2023-04-19 23:43:20,902 INFO    MainThread:8641 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/Uni Course/IML/IML_A3/wandb/run-20230419_234320-zgbe7e2n/logs/debug-internal.log
2023-04-19 23:43:20,902 INFO    MainThread:8641 [wandb_init.py:init():547] calling init triggers
2023-04-19 23:43:20,902 INFO    MainThread:8641 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-04-19 23:43:20,902 INFO    MainThread:8641 [wandb_init.py:init():595] starting backend
2023-04-19 23:43:20,902 INFO    MainThread:8641 [wandb_init.py:init():599] setting up manager
2023-04-19 23:43:20,906 INFO    MainThread:8641 [wandb_init.py:init():605] backend started and connected
2023-04-19 23:43:20,926 INFO    MainThread:8641 [wandb_run.py:_label_probe_notebook():1237] probe notebook
2023-04-19 23:43:20,927 INFO    MainThread:8641 [wandb_run.py:_label_probe_notebook():1247] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-04-19 23:43:20,927 INFO    MainThread:8641 [wandb_init.py:init():695] updated telemetry
2023-04-19 23:43:20,948 INFO    MainThread:8641 [wandb_init.py:init():732] communicating run to backend with 60.0 second timeout
2023-04-19 23:44:21,173 ERROR   MainThread:8641 [wandb_init.py:init():758] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-04-19 23:44:21,206 ERROR   MainThread:8641 [wandb_init.py:init():1163] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1145, in init
    run = wi.init()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 764, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-04-19 23:51:38,509 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Configure stats pid to 8641
2023-04-19 23:51:38,509 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from /Users/malujie/.config/wandb/settings
2023-04-19 23:51:38,510 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from /Users/Uni Course/IML/IML_A3/wandb/settings
2023-04-19 23:51:38,510 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-19 23:51:38,510 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-04-19 23:51:38,510 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-04-19 23:51:38,510 INFO    MainThread:8641 [wandb_init.py:_log_setup():507] Logging user logs to /Users/Uni Course/IML/IML_A3/wandb/run-20230419_235138-quia04bl/logs/debug.log
2023-04-19 23:51:38,511 INFO    MainThread:8641 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/Uni Course/IML/IML_A3/wandb/run-20230419_235138-quia04bl/logs/debug-internal.log
2023-04-19 23:51:38,511 INFO    MainThread:8641 [wandb_init.py:init():547] calling init triggers
2023-04-19 23:51:38,511 INFO    MainThread:8641 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-04-19 23:51:38,511 INFO    MainThread:8641 [wandb_init.py:init():595] starting backend
2023-04-19 23:51:38,511 INFO    MainThread:8641 [wandb_init.py:init():599] setting up manager
2023-04-19 23:51:38,517 INFO    MainThread:8641 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-04-19 23:51:38,521 INFO    MainThread:8641 [wandb_init.py:init():605] backend started and connected
2023-04-19 23:51:38,533 INFO    MainThread:8641 [wandb_run.py:_label_probe_notebook():1237] probe notebook
2023-04-19 23:51:38,551 INFO    MainThread:8641 [wandb_run.py:_label_probe_notebook():1247] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-04-19 23:51:38,571 INFO    MainThread:8641 [wandb_init.py:init():695] updated telemetry
2023-04-19 23:51:38,610 INFO    MainThread:8641 [wandb_init.py:init():732] communicating run to backend with 60.0 second timeout
2023-04-19 23:51:46,119 WARNING MainThread:8641 [wandb_init.py:init():1167] interrupted
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1145, in init
    run = wi.init()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 735, in init
    result = run_init_handle.wait(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-04-19 23:51:51,549 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Configure stats pid to 8641
2023-04-19 23:51:51,549 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from /Users/malujie/.config/wandb/settings
2023-04-19 23:51:51,549 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from /Users/Uni Course/IML/IML_A3/wandb/settings
2023-04-19 23:51:51,550 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-19 23:51:51,550 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-04-19 23:51:51,550 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-04-19 23:51:51,551 INFO    MainThread:8641 [wandb_init.py:_log_setup():507] Logging user logs to /Users/Uni Course/IML/IML_A3/wandb/run-20230419_235151-b75hrdq7/logs/debug.log
2023-04-19 23:51:51,551 INFO    MainThread:8641 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/Uni Course/IML/IML_A3/wandb/run-20230419_235151-b75hrdq7/logs/debug-internal.log
2023-04-19 23:51:51,551 INFO    MainThread:8641 [wandb_init.py:init():547] calling init triggers
2023-04-19 23:51:51,552 INFO    MainThread:8641 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-04-19 23:51:51,552 INFO    MainThread:8641 [wandb_init.py:init():595] starting backend
2023-04-19 23:51:51,552 INFO    MainThread:8641 [wandb_init.py:init():599] setting up manager
2023-04-19 23:51:51,557 INFO    MainThread:8641 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-04-19 23:51:51,563 INFO    MainThread:8641 [wandb_init.py:init():605] backend started and connected
2023-04-19 23:51:51,578 INFO    MainThread:8641 [wandb_run.py:_label_probe_notebook():1237] probe notebook
2023-04-19 23:51:51,578 INFO    MainThread:8641 [wandb_run.py:_label_probe_notebook():1247] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-04-19 23:51:51,578 INFO    MainThread:8641 [wandb_init.py:init():695] updated telemetry
2023-04-19 23:51:51,595 INFO    MainThread:8641 [wandb_init.py:init():732] communicating run to backend with 60.0 second timeout
2023-04-19 23:52:51,801 ERROR   MainThread:8641 [wandb_init.py:init():758] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-04-19 23:52:51,832 ERROR   MainThread:8641 [wandb_init.py:init():1163] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1145, in init
    run = wi.init()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 764, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-04-20 00:02:07,778 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Configure stats pid to 8641
2023-04-20 00:02:07,779 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from /Users/malujie/.config/wandb/settings
2023-04-20 00:02:07,779 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from /Users/Uni Course/IML/IML_A3/wandb/settings
2023-04-20 00:02:07,779 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-20 00:02:07,780 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-04-20 00:02:07,780 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-04-20 00:02:07,780 INFO    MainThread:8641 [wandb_init.py:_log_setup():507] Logging user logs to /Users/Uni Course/IML/IML_A3/wandb/run-20230420_000207-95q9gibw/logs/debug.log
2023-04-20 00:02:07,781 INFO    MainThread:8641 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/Uni Course/IML/IML_A3/wandb/run-20230420_000207-95q9gibw/logs/debug-internal.log
2023-04-20 00:02:07,781 INFO    MainThread:8641 [wandb_init.py:init():547] calling init triggers
2023-04-20 00:02:07,781 INFO    MainThread:8641 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-04-20 00:02:07,781 INFO    MainThread:8641 [wandb_init.py:init():595] starting backend
2023-04-20 00:02:07,782 INFO    MainThread:8641 [wandb_init.py:init():599] setting up manager
2023-04-20 00:02:07,783 INFO    MainThread:8641 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-04-20 00:02:07,785 INFO    MainThread:8641 [wandb_init.py:init():605] backend started and connected
2023-04-20 00:02:07,793 INFO    MainThread:8641 [wandb_run.py:_label_probe_notebook():1237] probe notebook
2023-04-20 00:02:07,794 INFO    MainThread:8641 [wandb_run.py:_label_probe_notebook():1247] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-04-20 00:02:07,794 INFO    MainThread:8641 [wandb_init.py:init():695] updated telemetry
2023-04-20 00:02:07,818 INFO    MainThread:8641 [wandb_init.py:init():732] communicating run to backend with 60.0 second timeout
2023-04-20 00:03:08,037 ERROR   MainThread:8641 [wandb_init.py:init():758] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-04-20 00:03:08,181 ERROR   MainThread:8641 [wandb_init.py:init():1163] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1145, in init
    run = wi.init()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 764, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-04-20 00:04:40,564 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Configure stats pid to 8641
2023-04-20 00:04:40,565 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from /Users/malujie/.config/wandb/settings
2023-04-20 00:04:40,565 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from /Users/Uni Course/IML/IML_A3/wandb/settings
2023-04-20 00:04:40,565 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-20 00:04:40,566 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-04-20 00:04:40,566 INFO    MainThread:8641 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-04-20 00:04:40,566 INFO    MainThread:8641 [wandb_init.py:_log_setup():507] Logging user logs to /Users/Uni Course/IML/IML_A3/wandb/run-20230420_000440-o3ttn2dv/logs/debug.log
2023-04-20 00:04:40,567 INFO    MainThread:8641 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/Uni Course/IML/IML_A3/wandb/run-20230420_000440-o3ttn2dv/logs/debug-internal.log
2023-04-20 00:04:40,567 INFO    MainThread:8641 [wandb_init.py:init():547] calling init triggers
2023-04-20 00:04:40,568 INFO    MainThread:8641 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-04-20 00:04:40,568 INFO    MainThread:8641 [wandb_init.py:init():595] starting backend
2023-04-20 00:04:40,569 INFO    MainThread:8641 [wandb_init.py:init():599] setting up manager
2023-04-20 00:04:40,571 INFO    MainThread:8641 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-04-20 00:04:40,576 INFO    MainThread:8641 [wandb_init.py:init():605] backend started and connected
2023-04-20 00:04:40,591 INFO    MainThread:8641 [wandb_run.py:_label_probe_notebook():1237] probe notebook
2023-04-20 00:04:40,591 INFO    MainThread:8641 [wandb_run.py:_label_probe_notebook():1247] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-04-20 00:04:40,592 INFO    MainThread:8641 [wandb_init.py:init():695] updated telemetry
2023-04-20 00:04:40,619 INFO    MainThread:8641 [wandb_init.py:init():732] communicating run to backend with 60.0 second timeout
2023-04-20 00:05:40,834 ERROR   MainThread:8641 [wandb_init.py:init():758] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-04-20 00:05:40,930 ERROR   MainThread:8641 [wandb_init.py:init():1163] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1145, in init
    run = wi.init()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 764, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
